name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
    paths:
      - "src/**"
  pull_request:
    branches: [main, master]
    paths:
      - "src/**"
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: 01yura/nbank-tests

jobs:
  build-and-test:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Получаем полную историю для получения commit hash

      - name: Check Docker Hub secrets
        run: |
          echo "=== Docker Hub Secrets Check ==="
          echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"
          echo "REGISTRY: ${{ env.REGISTRY }}"
          echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
          echo "Expected full image name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          echo "================================="
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "❌ ERROR: DOCKERHUB_USERNAME is empty or not set"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ ERROR: DOCKERHUB_TOKEN is empty or not set"
            exit 1
          fi
          echo "✅ Docker Hub secrets are configured"

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get commit hash
        id: commit_hash
        run: echo "hash=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Detect runner IP
        id: runner_ip
        run: |
          ip=$(hostname -I | awk '{print $1}')
          echo "Runner IP is: $ip"
          echo "ip=$ip" >> $GITHUB_OUTPUT

      - name: Set HOST_PATH for docker-compose
        run: |
          PROJECT_PATH=$(pwd)
          echo "Detected project path: $PROJECT_PATH"
          echo "HOST_PATH=$PROJECT_PATH" > infra/.env
          cat infra/.env

      - name: Set up services
        run: cd infra && bash restart_docker.sh && cd ..

      - name: Build project with Maven
        run: |
          echo "Building project..."
          ./mvnw clean compile -q
          echo "Build completed successfully"
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://${{ steps.runner_ip.outputs.ip }}:80
          UIREMOTE: http://localhost:4444/wd/hub

      - name: Run Checkstyle
        run: |
          echo "Running Checkstyle..."
          ./mvnw checkstyle:check -q
          echo "Checkstyle completed successfully"
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://${{ steps.runner_ip.outputs.ip }}:80
          UIREMOTE: http://localhost:4444/wd/hub

      - name: Run tests
        run: |
          echo "Running tests..."
          ./mvnw test -q
          echo "Tests completed successfully"
        env:
          APIBASEURL: http://localhost:4111
          UIBASEURL: http://${{ steps.runner_ip.outputs.ip }}:80
          UIREMOTE: http://localhost:4444/wd/hub

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.commit_hash.outputs.hash }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Docker image (PR only)
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.commit_hash.outputs.hash }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: target/surefire-reports/
          retention-days: 30

      - name: Upload Checkstyle results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: checkstyle-results
          path: target/checkstyle-result.xml
          retention-days: 30
